tree_mapping = {'POK':'Pedunculate Oak'
, 'ROK':'Red Oak'
, 'SOK':'Sessile Oak'
, 'SC':'Sweet Chestnut'
, 'SLI':'Small leaved Lime'
, 'CAR':'Common Alder'
, 'AH':'Ash'
, 'ASP':'Aspen'
, 'PBI':'Downy Birch'
, 'SBI':'Silver Birch'
, 'WCH':'Wild Cherry'
, 'WEM':'Wych Elm'
, 'HBM':'Hornbeam'
, 'SP':'Scotts Pine'
, 'BPO':'Black Poplar'
, 'ROW':'Rowan'
}